# Generated by Django 2.2.5 on 2022-05-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
