# Generated by Django 2.2.5 on 2022-05-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_auto_20220503_1323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='STUDENT',
        ),
    ]
