# Generated by Django 2.2.5 on 2022-05-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0003_auto_20220503_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='student',
            table='SOS_STUDENT',
        ),
    ]
